---
- name: Generate join command
  shell: >
    kubeadm token create --print-join-command
  register: join_command
  become: yes

- name: Set join command fact
  set_fact:
    join_command: "{{ join_command.stdout_lines[0] }}"
