---
- name: Generate join command
  ansible.builtin.shell: >
    kubeadm token create --print-join-command
  register: join_command
  become: true

- name: Set join command fact
  ansible.builtin.set_fact:
    join_command: "{{ join_command.stdout_lines[0] }}"
