[project]
name = "memoraq-infra"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible-lint>=25.9.0",
    "python-dateutil>=2.9.0.post0",
    "requests>=2.32.5",
]
