---
- name: Create servers for k8s cluster
  # host to execute the tasks on
  hosts: localhost
  #  skip ssh
  connection: local
  # skip os/package facts
  gather_facts: False
  vars:
    hcloud_token: {{API_TOKEN}}
  tasks:
    - name: Create control pane
      hcloud_server:
          api_token: "{{ hcloud_token }}"
          name: control-pane
          server_type: cx22
          image: ubuntu-24.04
          # Nuernberg datacenter
          location: nbg1
          state: present
      register: server
    - name: Create worker node
      hcloud_server:
          api_token: "{{ hcloud_token }}"
          name: worker-node
          server_type: cx22
          image: ubuntu-24.04
          location: nbg1
          state: present
      register: server
