---
- name: Set containerd as runtime for crictl
  shell: >
    crictl config --set runtime-endpoint=unix:///run/containerd/containerd.sock --set image-endpoint=unix:///run/containerd/containerd.sock
  become: yes
